version: '3.7'
services:
  previniendo-frontend:
    build:
      context: ./frontend/
      target: 'production-stage'
    image: previniendo-frontend
    container_name: previniendo-frontend
    restart: unless-stopped
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
      - ./media/:/media/
      - ./public/:/public/
    depends_on:
      - previniendo-backend
    ports:
      - 8000:80
  previniendo-backend:
    build:
      dockerfile: Dockerfile
      context: backend/
      args:
        requirements: requirements/produccion.txt
    image: previniendo-backend
    restart: unless-stopped
    container_name: previniendo-backend
    command: sh -c 'python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --worker-class=gevent --worker-connections=1000 --workers=3 --log-level=DEBUG config.wsgi:application --bind 0.0.0.0:8000'
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.produccion
      - GIT_COMMIT_SHA=${GIT_COMMIT_SHA}
    volumes:
      - ./media/:/media/
      - ./public/:/public/
