version: "3.7"
services:
  dev-previniendo-frontend:
    build:
      context: ./frontend/
      target: 'develop-stage'
    image: dev-previniendo-frontend
    container_name: dev-previniendo-frontend
    command: sh -c 'npm install && quasar dev'
    ports:
      - 9000:9000
    volumes:
      - ./frontend:/app
    restart: "no"
    depends_on:
      - dev-previniendo-backend
  dev-previniendo-backend:
    build:
      dockerfile: Dockerfile
      context: backend/
      args:
        requirements: requirements/desarrollo.txt
    image: dev-previniendo-backend
    restart: "no"
    container_name: dev-previniendo-backend
    command: sh -c 'python /app/manage.py migrate && python /app/manage.py runserver
      0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.desarrollo
    depends_on:
      - dev-previniendo-db
  dev-previniendo-db:
    restart: "no"
    image: postgres:alpine
    container_name: dev-previniendo-db
    ports:
      - 5439:5432
    environment:
      - POSTGRES_USER=previniendo
      - POSTGRES_PASSWORD=previniendo
      - POSTGRES_DB=previniendo
    volumes:
      - previniendo_postgresql_data_desarrollo:/var/lib/postgresql/data
volumes:
  previniendo_postgresql_data_desarrollo:
